In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Pima.csv")

In [4]:
df.head()

x1   x2  x3  x4   x5    x6     x7  x8  class
0   6  148  72  35    0  33.6  0.627  50      1
1   1   85  66  29    0  26.6  0.351  31      0
2   8  183  64   0    0  23.3  0.672  32      1
3   1   89  66  23   94  28.1  0.167  21      0
4   0  137  40  35  168  43.1  2.288  33      1

In [5]:
df.shape

(768, 9)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
x1       768 non-null int64
x2       768 non-null int64
x3       768 non-null int64
x4       768 non-null int64
x5       768 non-null int64
x6       768 non-null float64
x7       768 non-null float64
x8       768 non-null int64
class    768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [11]:
train = np.array(df.iloc[:600,:])

In [13]:
train

array([[6.00e+00, 1.48e+02, 7.20e+01, ..., 6.27e-01, 5.00e+01, 1.00e+00],
       [1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       ...,
       [1.00e+00, 8.90e+01, 2.40e+01, ..., 5.59e-01, 2.10e+01, 0.00e+00],
       [1.00e+00, 1.73e+02, 7.40e+01, ..., 8.80e-02, 3.80e+01, 1.00e+00],
       [1.00e+00, 1.09e+02, 3.80e+01, ..., 4.07e-01, 2.60e+01, 0.00e+00]])

In [16]:
test = np.array(df.iloc[600:,:])

In [15]:
test

array([[1.00e+00, 1.08e+02, 8.80e+01, ..., 4.00e-01, 2.40e+01, 0.00e+00],
       [6.00e+00, 9.60e+01, 0.00e+00, ..., 1.90e-01, 2.80e+01, 0.00e+00],
       [1.00e+00, 1.24e+02, 7.40e+01, ..., 1.00e-01, 3.00e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [20]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(train[:,:8],train[:,8])

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
predict = model.predict(test[:,0:8])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(test[:,8],predict)

0.7619047619047619

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train[:,:8],train[:,8])

C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
predict = model.predict(test[:,0:8])

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(test[:,8],predict)

0.7797619047619048

In [29]:
confusion_matrix(test[:,8],predict)

array([[98, 10],
       [27, 33]], dtype=int64)

In [32]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(train[:,:8],train[:,8])
predict = model.predict(test[:,0:8])

In [33]:
accuracy_score(test[:,8],predict)

0.6964285714285714

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(train[:,:8],train[:,8])
predict = model.predict(test[:,0:8])

C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [39]:
accuracy_score(test[:,8],predict)

0.7321428571428571

In [40]:
from sklearn.svm import SVC
model = SVC()
model.fit(train[:,:8],train[:,8])
predict = model.predict(test[:,0:8])

C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [41]:
accuracy_score(test[:,8],predict)

0.6428571428571429